PND/Controllers/PatientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PND.Models;
using System.Text;

namespace PND.Controllers
{
    [Authorize(Roles = "admin")]
    public class PatientController : Controller
    {
        
            private string url = "https://localhost:7022/api/Patient/";

        


        private HttpClient client = new HttpClient();

       
        [HttpGet]
            public IActionResult PIndex()
            {
                List<Patient> Patients = new List<Patient>();
                HttpResponseMessage response = client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    string result = response.Content.ReadAsStringAsync().Result;
                    var data = JsonConvert.DeserializeObject<List<Patient>>(result);
                    if (data != null)
                    {
                        Patients = data;
                    }
                }
                return View(Patients);
            }


        [Authorize(Roles = "admin")]
        [HttpGet]
            public IActionResult AddPatient()
            {
                return View();
            }

            [HttpPost]
            public IActionResult AddPatient(Patient pct)
            {
                string data = JsonConvert.SerializeObject(pct);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = client.PostAsync(url, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["insert_message"] = "Patient Added ..";
                    return RedirectToAction("PIndex");
                }
                return View();
            }
        [Authorize(Roles = "admin")]
        [HttpGet]
            public IActionResult Edit(int id)
            {
                Patient pct = new Patient();
                HttpResponseMessage response = client.GetAsync(url + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string result = response.Content.ReadAsStringAsync().Result;
                    var data = JsonConvert.DeserializeObject<Patient>(result);
                    if (data != null)
                    {
                        pct = data;
                    }
                }
                return View(pct);
            }
        [Authorize(Roles = "admin")]
        [HttpPost]
            public IActionResult Edit(Patient pct)
            {
                string data = JsonConvert.SerializeObject(pct);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = client.PutAsync(url + pct.PatientID, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["Update_message"] = "Patient Updated ..";
                    return RedirectToAction("PIndex");
                }
                return View();
            }
        

        [HttpGet]
        public IActionResult Details(int id)
        {
            Patient pct = new Patient();
            HttpResponseMessage response = client.GetAsync(url + id).Result;
            if (response.IsSuccessStatusCode)
            {
                string result = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<Patient>(result);
                if (data != null)
                {
                    pct = data;
                }
            }
            return View(pct);
        }
    
            [Authorize(Roles = "admin")]
        [HttpGet]
            public IActionResult Delete(int id)
            {
                Patient pct = new Patient();
                HttpResponseMessage response = client.GetAsync(url + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string result = response.Content.ReadAsStringAsync().Result;
                    var data = JsonConvert.DeserializeObject<Patient>(result);
                    if (data != null)
                    {
                        pct = data;
                    }
                }
                return View(pct);
            }
        [Authorize(Roles = "admin")]

        [HttpPost, ActionName("Delete")]
            public IActionResult DeleteConfirmed(int id)
            {

                HttpResponseMessage response = client.DeleteAsync(url + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["Delete_message"] = "Patient Deleted ..";
                    return RedirectToAction("PIndex");
                }
                return View();
            }




        }
    }

PND/Controllers/UserPatientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PND.Areas.Identity.Data;
using PND.Models;
using System.Text;


namespace PND.Controllers
{
    public class UserPatientController : Controller
    {
        private readonly SignInManager<PNDUser> signInManager;
        private readonly UserManager<PNDUser> userManager;
        private string url = "https://localhost:7022/api/Patient/";
        private string appointmentUrl = "https://localhost:7022/api/Appointment/";


        private HttpClient client = new HttpClient();

        public UserPatientController(SignInManager<PNDUser> SignInManager, UserManager<PNDUser> UserManager)
        {
            signInManager = SignInManager;
            userManager = UserManager;
        }

        [HttpGet]
        public IActionResult Details()
        
        {
            var mail = userManager.GetUserName(User);
            var patientDetails = new PatientViewModel();
            HttpResponseMessage response = client.GetAsync(url+ "GetPatientDetailsBymail/" + mail ).Result;
            if (response.IsSuccessStatusCode)
            {
                string result = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<Patient>(result);

                if (data != null)
                {
                    var appointments = new List<Appointment>();
                    var dd = appointmentUrl + "GetPatientAppointmets/" + data.PatientID;
                    HttpResponseMessage appointmentResponse = client.GetAsync(dd).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        string appointmentResult = appointmentResponse.Content.ReadAsStringAsync().Result;
                        var appointmentData = JsonConvert.DeserializeObject<List<Appointment>>(appointmentResult);

                        if (appointmentData != null)
                        {
                            appointments = appointmentData;
                        }
                    }
                    patientDetails.Patient = data;
                    patientDetails.Appointments = appointments;
                    //pct = data;
                }
            }

            return View(patientDetails);
        }

        [HttpPost]
        public IActionResult GetPatient(int patientId)
        {
            var patientDetails = new PatientViewModel();
            HttpResponseMessage response = client.GetAsync(url + patientId).Result;
            if (response.IsSuccessStatusCode)
            {
                string result = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<Patient>(result);

                if (data != null)
                {
                    var appointments = new List<Appointment>();
                    var dd = appointmentUrl + "GetPatientAppointmets/" + data.PatientID;
                    HttpResponseMessage appointmentResponse = client.GetAsync(dd).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        string appointmentResult = appointmentResponse.Content.ReadAsStringAsync().Result;
                        var appointmentData = JsonConvert.DeserializeObject<List<Appointment>>(appointmentResult);
                          
                        if (appointmentData != null)
                        {
                            appointments = appointmentData;
                        }
                    }
                    patientDetails.Patient = data;
                    patientDetails.Appointments = appointments;
                        //pct = data;
                }
            }
            return View("Details", patientDetails);
        }

    }
}

PND/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PND.Areas.Identity.Data

@inject SignInManager<PNDUser> SignInManager
@inject UserManager<PNDUser> UserManager

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PND</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PND.styles.css" asp-append-version="true" />
</head>
<body>
    
     @* @if (SignInManager.IsSignedIn(User))
    {
        string mail = @UserManager.GetUserName(User);
        string admin = "admin@gmail.com";
       
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PND Portal</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    }

                   @*  <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> 
                         <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="doctor" asp-action="Index">users</a>
                        </li> 
                            @if (mail=="admin@gmail.com") {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="PIndex">Admin</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserPatient" asp-action="Details">Patient</a>
                                </li>
                            
                            }
                            else
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserPatient" asp-action="Details">Patient</a>
                            </li> 
                            }
                        </ul>
                    </div>
                    <partial name="_LoginPartial" />
                </div> 
            </nav>
        </header>
    } 
    else  *@
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PND Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                  
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PND - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>